# server port
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_toyboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rlawldnjs12

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml


