# server port
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
    context-path: /

# database
spring:
  datasource:
# cafe24
    driver-class-name: com.mysql.jdbc.Driver
#localhost8080
#    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:mysql://localhost:3306/db_toyboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mariadb://localhost/treecommunity?useSSL=false
#    url: jdbc:mariadb://treecommunity.cafe24.com:3306/treecommunity
#    url: jdbc:mariadb://treecommunity.cafe24.com:3306/treecommunity?serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
#    localhost
#    url: jdbc:mysql://localhost:3306/db_toyboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: rlawldnjs12

# cafe24
    url: jdbc:mysql://localhost:3306/treecommunity
    username: treecommunity
    password: as962680!

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml


